services:
    staticform:
        build: .
        ports:
            - "4000:5000"
        environment:
            SF_PORT: 5000
            SF_ENV: dev
            SF_SMTP_HOST: mailpit
            SF_SMTP_PORT: 1025
            SF_SMTP_TLS: none
            SF_SMTP_FROM: forms@example.com
            SF_SMTP_RECEIVER: john@example.com

    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        volumes:
            - ./data:/data
        ports:
            - "8025:8025"
            - "1025:1025"
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
